import './globals.css';
import {Inter} from 'next/font/google';
import Footer from '../components/global/footer';
import Header from "../components/global/header";

const inter = Inter({ subsets: ['latin'] });

// @ts-ignore
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps): JSX.Element {

  return (
    <html lang="en">
    <body className={inter.className}>
    <Header/>
      {children}
    <Footer/>
    </body>
    </html>
  );
}
